onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/DUT/CPU/DP/CLK
add wave -noupdate /system_tb/DUT/CPU/DP/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/PC_en
add wave -noupdate /system_tb/DUT/CPU/DP/negative
add wave -noupdate /system_tb/DUT/CPU/DP/overflow
add wave -noupdate /system_tb/DUT/CPU/DP/zero
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/a
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/b
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/aluop
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/negative
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/overflow
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/zero
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/out
add wave -noupdate /system_tb/DUT/CPU/DP/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/opcode
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/funct
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/PC_src
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Ext_src
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/LUI_src
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/portb_src
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegDst
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegWEN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALU_op
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemWrite
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemRead
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemtoReg
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/PC_EN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Zero
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Overflow
add wave -noupdate /system_tb/DUT/CPU/DP/PC_next
add wave -noupdate /system_tb/DUT/CPU/DP/PC
add wave -noupdate /system_tb/DUT/CPU/DP/out
add wave -noupdate /system_tb/DUT/CPU/DP/j_inst
add wave -noupdate /system_tb/DUT/CPU/DP/i_inst
add wave -noupdate /system_tb/DUT/CPU/DP/r_inst
add wave -noupdate /system_tb/DUT/CPU/DP/signedExt
add wave -noupdate /system_tb/DUT/CPU/DP/zeroExt
add wave -noupdate /system_tb/DUT/CPU/DP/jumpExt
add wave -noupdate /system_tb/DUT/CPU/DP/shamtExt
add wave -noupdate /system_tb/DUT/CPU/DP/luiExt
add wave -noupdate /system_tb/DUT/CPU/DP/PC_plus4
add wave -noupdate /system_tb/DUT/CPU/DP/PC_branch
add wave -noupdate /system_tb/DUT/CPU/DP/PC_reg
add wave -noupdate /system_tb/DUT/CPU/DP/PC_jump
add wave -noupdate /system_tb/DUT/CPU/DP/halt_reg
add wave -noupdate /system_tb/DUT/CPU/DP/RWD_out
add wave -noupdate /system_tb/DUT/CPU/DP/IntoMem
add wave -noupdate /system_tb/DUT/CPU/DP/extended_imm
add wave -noupdate /system_tb/DUT/CPU/DP/portb_mux_out
add wave -noupdate /system_tb/DUT/CPU/DP/PC_out
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/datomic
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate /system_tb/DUT/RAM/ramif/ramREN
add wave -noupdate /system_tb/DUT/RAM/ramif/ramWEN
add wave -noupdate /system_tb/DUT/RAM/ramif/ramaddr
add wave -noupdate /system_tb/DUT/RAM/ramif/ramstore
add wave -noupdate /system_tb/DUT/RAM/ramif/ramload
add wave -noupdate /system_tb/DUT/RAM/ramif/ramstate
add wave -noupdate /system_tb/DUT/RAM/ramif/memREN
add wave -noupdate /system_tb/DUT/RAM/ramif/memWEN
add wave -noupdate /system_tb/DUT/RAM/ramif/memaddr
add wave -noupdate /system_tb/DUT/RAM/ramif/memstore
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {39180 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 162
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {213583 ps}
